#name: todo_app
#description: A modern TODO app with clean UI/UX
#version: 1.0.0
#environment:
#  sdk: '>=3.0.0 <4.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#  flutter_riverpod: ^2.3.6
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  http: ^1.1.0
#  google_fonts: ^6.1.0
#  lottie: ^3.1.0
#  intl: ^0.19.0
#  flutter_slidable: ^3.1.0
#  flutter_staggered_grid_view: ^0.7.0
#  go_router: ^14.0.0
#  json_serializable: ^6.7.1
#  json_annotation: ^4.8.1
#  flutter_hooks: ^0.20.0
#  path_provider: ^2.1.0
#  path: ^1.8.0
#  freezed_annotation: ^2.2.0
#  email_validator: ^2.1.17
#  uuid: ^4.0.0
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  build_runner: ^2.4.6
#  hive_generator: ^2.0.0
#  freezed: ^2.3.2
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/lottie/

name: flutter_todo_app
description: A modern Flutter todo list application with beautiful UI and local storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

